[package]
name = "thin-logger"
version = "0.1.0"
edition = "2024"
description = "A thin logger wrapper around env_logger with customizable formatting and filtering."
license = "MIT"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
anyhow = "1.0"
chrono = "0.4.40"
colored = "3.0.0"
